# Generated by Django 2.1.1 on 2019-11-05 08:31

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CombinationRestriction',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('project_type1', models.IntegerField()),
                ('project_type2', models.IntegerField()),
                ('restriction', models.BooleanField(choices=[(True, ' is only allowed with '), (False, ' is not allowed with ')])),
            ],
        ),
        migrations.CreateModel(
            name='SavedFlowcell',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fc_id', models.CharField(max_length=15)),
                ('jsonified_flowcell', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='StagedSample',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sample_id', models.IntegerField()),
                ('nmol', models.FloatField()),
                ('megareads', models.FloatField()),
                ('priority', models.IntegerField()),
                ('remark', models.CharField(default='', max_length=100)),
            ],
        ),
    ]
